"""Persisted runtime settings keys (formerly internal.sh)."""

from __future__ import annotations

# Keys written to STATE/settings.ini (exclude launch-only fields).
SETTINGS_KEYS: tuple[str, ...] = (
    "batchmode",
    "colormode",
    "repodate",
    "compname",
    "rundir",
    "langid",
    "have_altsp",
    "have_systemd",
    "install_mate",
    "distroname",
    "distro",
    "repo",
    "have_xorg",
    "have_kde5",
    "have_mate",
    "have_xfce",
    "have_gnome",
    "archname",
    "pctype",
    "drives",
    "ifaces",
    "fwupd_test",
    "devel_test",
    "xprss_test",
    "infb_test",
    "sound_test",
    "numa_test",
    "ipmi_test",
    "webcam_test",
    "power_test",
    "fprnt_test",
    "bluez_test",
    "scard_test",
    "fio_test",
    "v3d_test",
    "update_apt_lists",
    "dist_upgrade",
    "update_kernel",
    "local_url",
    "local_mirror",
    "mirror_subdir",
    "local_media_base",
    "local_media_check",
    "unsafe_diskperf",
    "disable_autorun",
    "ping_server",
    "express_video_set",
    "local_video_sample",
)
